### ISSUE TITLE
You have requested a non-existent service "translation_plugin_service".

### ISSUE THREAD

**Issue by joaonzangoII** [yaroslavche/sylius-translation-plugin#1]
Cannot use plugin,

**Comment by yaroslavche** [comment]
Can you provide more info?
What version of Sylius do you have?
Are you sure that service is registered and config is imported?

Also I don't test plugin on new Sylius based on Symfony 4. If you use newest, then you can try to inject service in method like this:
```php
use Acme\SyliusTranslationPlugin\Service\TranslationPlugin;
public function dashboardAction(TranslationPlugin $translationPlugin)
{
    // and comment this line
    // $translationPlugin = $this->get('translation_plugin_service');
    // ...
}
```

**Comment by yaroslavche** [comment]
I tried to install the latest stable Sylius and plugin. However, unlike you, I had versions 1.2.4 and 4.1.2.

Please try adding the `_defaults` section to services config
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # plugin service
    # ...
```
in file `{project_path}/vendor/yaroslavche/sylius-translation-plugin/src/Resources/config/services.yml` and let me know if it helps.
